config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :courts, only: [:index, :show, :new, :create] do
    resources :events do
      resources :event_users, only: [:new, :create, :destroy] do
        resources :reviews, only: [:index, :new, :create]
      end
    end
  end

  resources :dashboards, only: [:show, :edit, :update]

  get '/profile/:username', to: 'pages#profile', as: 'profile'

  resources :chats, only: [:index, :show, :create] do
     resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :court
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users

  def is_user_registered?(user_id)
    self.event_users.where(user_id: user_id).count != 0
  end

  def is_event_full?
    self.event_user_ids.count == self.num_of_players
  end

  def is_past_event?
    self.date < DateTime.now.change(offset: "-0000") # changed offset for calculation
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_court, only: [:index, :show, :new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @events = policy_scope(Event).where(court_id: params[:court_id]).order(date: :desc)
  end

  def show
    @user = User.find(@event.user_id)
    unless current_user.nil?
      @event_user = EventUser.find_by(event_id: params[:id], user_id: current_user.id)
      unless @event_user.nil?
        authorize @event_user
      end
    end
  end

  def avg_rating(id)
    Review.where(rated_event_user_id: id).average(:rating).to_f
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    if @court.events.create(event_params.merge(user_id: current_user.id))
      redirect_to court_path(@court)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to court_events_path
    else
      render :edit
    end
  end

  # def destroy
  # end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :price_cents, :num_of_players, :time)
  end

  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def set_court
    @court = Court.find(params[:court_id])
    authorize @court
  end
end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10-col-sm-12 form-signin mt-3">
      <%= form_for([@court, @event]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :date %>
        <%= f.datetime_field :date, class: 'form-control timepicker'%>
      </div>

      <div class="form-group">
        <%= f.label :num_of_players %>
        <%= f.number_field :num_of_players, class: 'form-control' %>
      </div>

      <%= f.submit class: 'all-buttons pink-button text-center large-button' %>
    <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10-col-sm-12 form-signin mt-5">
      <h3 class="text-center mt-3"><%= @event.name %></h3>
      <%= form_for @event, url: court_event_path(court_id: params[:court_id], event_id: params[:id]) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :date %>
          <%= f.datetime_field :date, class: 'form-control timepicker'%>
        </div>

        <div class="form-group">
          <%= f.label :num_of_players %>
          <%= f.text_field :num_of_players, class: 'form-control' %>
        </div>

        <%= f.submit "Edit", class: 'all-buttons pink-button text-center large-button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container gray-back">
  <h5 class="text-center text-secondary pt-2"><%= @court.name %></h3>
  <h3 class="text-center">Events</h3>

  <div class="row">
  <% @events.each do |event| %>
    <% if !event.is_past_event? %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card-rale white-back mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= event.name %></h5>
            <p class="card-subtitle mb-2"><%= event.description %></h6>
            <div class="d-flex justify-content-between mb-3">
              <p class="card-text"><i class="far fa-calendar-alt mr-2"></i> <%= event.date.strftime('%d/%m/%Y') %></p>
              <p class="card-text"><i class="fas fa-users mr-2"></i> <%= event.event_users.count %> / <%= event.num_of_players %></p>
              <p class="card-text"><i class="far fa-clock mr-2"></i> <%= event.time == nil ? "00:00" : event.date.strftime('%H:%M') %></p>
            </div>
            <%= link_to "More details", court_event_path(event.court, event), class: "all-buttons pink-button btn-block text-center"%>
          </div> <!--  END OF CARD BODY -->
        </div> <!--  END OF CARD RALE -->
      </div><!--  END OF COL -->
    <% end %>
  <% end %>
  </div><!--  END OF ROW -->

  <h3 class="text-center">Past events</h3>

  <div class="row">
    <% @events.each do |event| %>
      <% if event.is_past_event? %>
        <div class="col-lg-4 col-md-6 col-sm-12">
          <div class="card white-back mb-3">
            <div class="card-body">
              <h5 class="card-title"><%= event.name %></h5>
              <p class="card-subtitle mb-2"><%= event.description %></h6>
              <div class="d-flex justify-content-between">
                <p class="card-text"><i class="far fa-calendar-alt mr-2"></i> <%= event.date.strftime('%d/%m/%Y') %></p>
                <p class="card-text"><i class="fas fa-users mr-2"></i> <%= event.event_users.count %> / <%= event.num_of_players %></p>
                <p class="card-text"><i class="far fa-clock mr-2"></i> <%= event.time == nil ? "00:00" : event.date.strftime('%H:%M') %></p>
              </div>
              <%= link_to "More details", court_event_path(event.court, event), class: "all-buttons black-button btn-block text-center"%>
            </div>
          </div>
        </div><!--  END OF COL -->
      <% end %>
    <% end %>
  </div><!--  END OF ROW -->
</div>

app/views/events/new.html.erb
<div class="container">
  <h3 class="text-center mt-3">New event</h3>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="event-header pb-3">
  <div class="container">
    <h2 class="text-center pt-4 mb-2"><%= @event.name %></h2>
    <p class="created-by text-center">Created by <strong><%= link_to @user.username, profile_path(@user.username) %></strong>
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, class: "nav-avatar ml-1" %>
      <% else %>
        <img class="nav-avatar ml-1" src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80">
      <% end %>
    </p>

    <% if current_user != @user %>
      <p class="text-center message"><span class="msg-link"><%= link_to "Message #{@user.username}", chats_path(sender_id: current_user, recipient_id: @user.id), method: :post %><i class="far fa-comment-dots ml-2"></i></span></p>
    <% end %>

    <p class="text-center my-4 location"><i class="fas fa-map-marker-alt"></i> <span class="ml-3"><%= @event.court.address %></span></p>
    <div class="d-flex justify-content-around event-info">
      <p><i class="far fa-calendar-alt"></i> <span class="ml-3"><%= @event.date.strftime('%d/%m/%Y') %></span></p>
      <p><i class="far fa-clock"></i> <span class="ml-3"><%= @event.date.strftime('%H:%M') %></span></p>
      <p><i class="fas fa-users"></i> <span class="ml-3"><%= @event.event_users.count %> / <%= @event.num_of_players %></span></p>
    </div>

  </div> <!-- END OF CONTAINER 1 -->
</div>


<div class="container">

  <% if @event.is_past_event? %>
    <h5 class="text-center mt-4 text-danger">Event expired. You can't join anymore!</h5>
  <% end %>

  <div class="d-flex justify-content-around pt-3">
    <% if current_user %>
      <% if @event.is_event_full? || @event.is_past_event? %>
        <%= button_to "Join Event", court_event_event_users_path(@court, @event), method: :post, class: "large-button text-center disabled-button", disabled: true %>
      <% elsif @event.is_user_registered?(current_user.id) %>
          <% if policy(@event_user).destroy? %>
            <%= button_to "Leave event", court_event_event_user_path(@court, @event), class: "all-buttons black-button large-button text-center", action: :destroy, method: :delete %>
          <% end %>
      <% else %>
        <%= button_to "Join Event", court_event_event_users_path(@court, @event), method: :post, class: "all-buttons pink-button large-button text-center" %>
      <% end %>
    <% else %>
      <%= button_to "Join Event", court_event_event_users_path(@court, @event), method: :post, class: "all-buttons pink-button large-button text-center" %>
    <% end %>
    <% if current_user %>
      <% if policy(@event).edit? && !@event.is_past_event? %>
        <%= link_to "Edit", edit_court_event_path(@court, @event), class: "all-buttons white-button white-button-outline large-button text-center" %>
      <% end %>
    <% end %>
  </div> <!-- END OF D-FLEX DIV FOR BUTTONS -->


  <div class="players-joined pt-3">
    <p class="text-center">Players joined ( <%= @event.event_users.count %> ):</p>
      <% @event.event_users.each do |event_user| %>
        <div class="border-bottom players-list mb-2 p-3 d-flex justify-content-between">
          <div class="player">
            <% if event_user.user.photo.attached? %>
              <%= cl_image_tag event_user.user.photo.key, class: "nav-avatar my-1" %>
            <% else %>
              <img class="nav-avatar my-1" src="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80">
            <% end %>
            <span class="mx-3"><%= link_to event_user.user.username, profile_path(event_user.user.username) %></span>
            <span><i class="far fa-star mr-1"></i> <%= event_user.user.avg_rating.floor(2) %> / 10</span>
            <span class="ml-3">Total num of reviews: <%= event_user.user.number_of_reviews %></span>
          </div>
          <div>
            <% if current_user && @event.is_past_event?%>
            <% if @event.is_user_registered?(current_user.id) %>
              <% if !event_user.is_event_user_rated?(event_user.id, current_user.id, event_user.user.id) %>
                <% if current_user.id != event_user.user.id %>
                  <%= link_to "Rate", new_court_event_event_user_review_path(event_id: params[:id], event_user_id: event_user.id), class: "" %>
                <% end %>
              <% else %>
                <% event_user.reviews.each do |review| %>
                  <% if review.rated_event_user_id == event_user.user.id && review.rating_event_user_id == current_user.id %>
                  <p>Your rating: <%= review.rating %></p>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          </div>
        </div>
      <% end %>
  </div> <!-- END OF PLAYERS JOINED DIV -->
</div> <!-- END OF CONTAINER 2 -->