config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :courts, only: [:index, :show, :new, :create] do
    resources :events do
      resources :event_users, only: [:new, :create, :destroy] do
        resources :reviews, only: [:index, :new, :create]
      end
    end
  end

  resources :dashboards, only: [:show, :edit, :update]

  get '/profile/:username', to: 'pages#profile', as: 'profile'

  resources :chats, only: [:index, :show, :create] do
     resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'
end

app/models/court.rb
class Court < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :events

  validates :name, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :court_type, presence: true, inclusion: { in: %w(indoor outdoor) }
  has_one_attached :photo
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :set_court, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index         # GET /courts
    if params[:query].present?
    sql_query = "name ILIKE :query OR address ILIKE :query"
    @courts = policy_scope(Court).where(sql_query, query: "%#{params[:query]}%")
    else
      @courts = policy_scope(Court).all
    end
  end

  def show          # GET /courts/:id
    @event_user = EventUser.new
  end

  def new           # GET /courts/new
    @court = Court.new
    authorize @court
  end

  def create        # POST /courts
    @court = Court.new(court_params.merge(user_id: current_user.id))
    authorize @court

    if @court.save
      redirect_to courts_path
    else
      render :new
    end
  end

  # def edit          # GET /courts/:id/edit
  # end

  # def update        # PATCH /courts/:id
  # end

  # def destroy       # DELETE /courts/:id
  # end

  private

  def court_params
    params.require(:court).permit(:name, :description, :address, :court_type, :capacity, :photo)
  end

  def set_court
    @court = Court.find(params[:id])
    authorize @court
  end
end

app/views/courts/index.html.erb
<div class="container">
  <h3 class="mt-3 text-center">List of all courts</h3>
  <div class="d-flex justify-content-between my-3">
    <div class="search-bar-sm">
      <%= form_tag courts_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: "Search for court name or address...",
          class: "search-bar" %>
    </div>
    <div class="search-btn-sm">
      <%= button_tag(type: "submit", class: "all-buttons pink-button btn-block") do %>
            <i class="fas fa-search"></i>
      <% end %>
    </div>
  </div>
      <% end %>

  <div class="row">
    <% @courts.each do |court| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
          <div class="card-rale mb-3">

              <div class="card-top">
                <%= link_to court_path(court) do %>
                  <div class="image-top">
                    <% if court.photo.attached? %>
                      <%= cl_image_tag court.photo.key, class: "card-img-top" %>
                    <% else %>
                      <img class="card-img-top" src="https://images.unsplash.com/photo-1523225078415-687408717027?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=745&q=80" alt="Card image cap">
                    <% end %>
                  </div> <!-- END OF IMAGE TOP -->

                  <div class="card-body pt-4 px-4">
                    <h4 class="card-title"><%= court.name %></h4>
                    <p class="card-text"><i class="fas fa-map-marker-alt"></i> <span class="ml-2"><%= court.address %></span></p>
                    <!-- <p class="card-text"><i class="fas fa-user"></i> <span class="ml-2"><%= court.capacity %></span></p> -->
                  </div> <!-- END OF CARD BODY -->
                <% end %>
              </div> <!-- END OF CARD TOP -->

              <div class="card-buttons pb-4 d-flex justify-content-around ">
                <%= link_to "Check events", court_events_path(court), class: "all-buttons pink-button" %>
                <%= link_to "Create Event", new_court_event_path(court), class: "all-buttons black-button" %>
              </div> <!-- END OF CARD BUTTON -->







        </div> <!-- END OF CARD -->
      </div> <!-- END OF COL -->
    <% end %>
  </div> <!-- END OF ROW -->
</div> <!-- END OF CONTAINER -->

app/views/courts/new.html.erb
<div class="text-center">
  <div class="form-signin mt-5">
    <h3>New court</h3>

    <%= simple_form_for(@court) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :court_type %>
        <%= f.text_field :court_type, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :capacity %>
        <%= f.text_field :capacity, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :photo, as: :file, class: 'form-control' %>
      </div>

      <%= f.submit class: 'all-buttons text-center pink-button large-button' %>
    <% end %>
  </div> <!-- END OF FORM SIGNIN -->
</div> <!-- END OF TEXT-CENTER -->

app/views/courts/show.html.erb
<div class="header">
  <div class="court-img">
    <% if @court.photo.attached? %>
      <%= cl_image_tag @court.photo.key %>
    <% else %>
      <img src="https://images.unsplash.com/photo-1523225078415-687408717027?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=745&q=80" alt="Card image cap">
    <% end %>
  </div>
  <div class="court-description mt-4">
    <h3 class="text-center"><%= @court.name %></h3>
    <h5 class="mb-4 text-center"><i class="fas fa-map-marker-alt"></i> <%= @court.address %></h5>
  </div>
</div>

<div class="container">
  <p class="mt-3"><%= @court.description %></p>
  <div class="bottom-btn">
    <%=  link_to "Create Event", new_court_event_path(@court), class: "all-buttons pink-button text-center btn-block" %>
  </div>
</div>
<div class="container gray-back mt-4">
  <h4 class="text-center pt-3 mb-4">Events</h4>
  <% if @court.events.empty? %>
    <p>There are no events for this court.</p>
    <%= link_to "Create Event", new_court_event_path(@court), class: "all-buttons black-button-sm" %>
  <% else %>
    <div class="row">
        <% @court.events.order(date: :desc).each do |event| %>
        <% if !event.is_past_event? %>
          <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card-rale white-back mb-3">
                <div class="card-body">
                  <h4 class="card-title"><%= event.name %></h4>
                  <div class="d-flex justify-content-around event-info">
                    <p><i class="far fa-calendar-alt"></i> <span class="card-text mb-2 ml-2"> <%= event.date.strftime('%d/%m/%Y') %></span></p>
                    <p><i class="far fa-clock"></i> <span class="card-text ml-2"><%= event.date.strftime('%H:%M') %></span></p>
                    <p><i class="fas fa-users"></i><span class="card-text ml-2"> <%= event.event_users.count %> / <%= event.num_of_players %></span></p>
                  </div>
                  <%= link_to "Check details", court_event_path(@court, event), class: "all-buttons text-center white-button white-button-outline btn-block" %>
                </div>
            </div>
          </div><!--  END OF COL -->
        <% end %>
      <% end %>
    </div><!--  END OF ROW -->

    <h4 class="text-center my-5">Past events</h4>
    <div class="row">
        <% @court.events.order(date: :desc).each do |event| %>
          <% if event.is_past_event? %>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="card-rale white-back mb-3">
                  <div class="card-body">
                    <h4 class="card-title"><%= event.name %></h4>
                    <div class="d-flex justify-content-around event-info">
                    <p><i class="far fa-calendar-alt"></i> <span class="card-text mb-2 ml-2"> <%= event.date.strftime('%d/%m/%Y') %></span></p>
                    <p><i class="far fa-clock"></i> <span class="card-text ml-2"><%= event.date.strftime('%H:%M') %></span></p>
                    <p><i class="fas fa-users"></i><span class="card-text ml-2"> <%= event.event_users.count %> / <%= event.num_of_players %></span></p>
                  </div>
                    <%= link_to "Check details", court_event_path(@court, event), class: "all-buttons text-center black-button btn-block" %>
                  </div>
              </div>
            </div><!--  END OF COL -->
          <% end %>
        <% end %>
    </div><!--  END OF ROW -->

  <% end %>

</div>