config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :courts, only: [:index, :show, :new, :create] do
    resources :events do
      resources :event_users, only: [:new, :create, :destroy] do
        resources :reviews, only: [:index, :new, :create]
      end
    end
  end

  resources :dashboards, only: [:show, :edit, :update]

  get '/profile/:username', to: 'pages#profile', as: 'profile'

  resources :chats, only: [:index, :show, :create] do
     resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'
end

app/views/pages/_info_window.html.erb
<div class="pin-content">
  <div class="pin-text">
    <%= link_to court_path(court) do %>
      <h6><%= court.name %></h6>
      <p><%= court.address %></p>
    <% end %>
  </div>
<%= link_to "Add event", new_court_event_path(court), class: "all-buttons btn-block pink-button text-center" %>
</div>

app/views/pages/home.html.erb
<div class="hero pt-2 pb-5">
  <div class="container">
    <div id="lading-page-text" class="mt-5 mx-3">
      <h2 class="pt-5">Find the best pickup game near you.</h2>
      <div class="row mt-5">
        <div class="col-lg-6 col-sm-12">
          <%= form_tag courts_path, method: :get do %>
            <%= text_field_tag :query,
                params[:query],
                placeholder: "Search for court name or address...",
                class: "search-bar" %>
        </div> <!-- END OF COL -->
      </div> <!-- END OF ROW -->
      <div class="d-flex pt-3 pb-5">
          <%= submit_tag "Search", class: "all-buttons large-button black-button text-center mr-3"%>
          <a href="#" class="all-buttons large-button white-button text-center scroll-down">Check map</a>
      </div>
          <% end %>
    </div> <!-- END OF LANDING-PAGE-TEXT -->
  </div> <!-- END OF CONTAINER -->
</div> <!-- END OF HERO -->

<div class="map-display py-5" id="second">
  <div class="container">
    <h3 class="text-center mb-5">Check courts on the map</h3>
    <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div> <!-- END OF CONTAINER -->
  <div class="links d-flex justify-content-center my-5">
    <%= link_to "Add court", new_court_path, class: "all-buttons large-button black-button text-center mr-5" %>
    <%= link_to "See all courts", courts_path, class: "all-buttons large-button white-button white-button-outline text-center ml-5" %>
  </div>
</div> <!-- END OF MAP DISPLAY -->

<script>
  function smoothScroll(scrollTo, duration) {
    let scroll = document.querySelector(scrollTo);
    let scrollPosition = scroll.getBoundingClientRect().top + window.scrollY;
    let startPosition = window.pageYOffset;
    let distance = scrollPosition - startPosition;
    let startTime = null;

    function animation(currentTime) {
      if(startTime === null) startTime = currentTime;
      let timeElapsed = currentTime - startTime;
      let run = ease(timeElapsed,startPosition,distance,duration);
      window.scrollTo(0,run);
      if(timeElapsed < duration) requestAnimationFrame(animation);
    }

    function ease(t, b, c, d) {
      t /= d;
      return -c * t*(t-2) + b;
    };

    requestAnimationFrame(animation)
  }

  let scrollBtn = document.querySelector('.scroll-down')
  scrollBtn.addEventListener('click', function() {
    smoothScroll('#second', 200)
  })

</script>




























<!--  -->

app/views/pages/profile.html.erb
<h3><%= @user.username %></h3>
<p><%= @user.email %></p>
<ul>
  <% @reviews.each do |review| %>
    <li>
      Rating: <%= review.rating %> /
      Rated by: <%= review.event_user.event.users.find(review.rating_event_user_id).username  %> /
      Event: <%= review.event_user.event.name %> /
      Court: <%= review.event_user.event.court.name %>, <%= review.event_user.event.court.address %>
    </li>
  <% end %>
</ul>