config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :courts, only: [:index, :show, :new, :create] do
    resources :events do
      resources :event_users, only: [:new, :create, :destroy] do
        resources :reviews, only: [:index, :new, :create]
      end
    end
  end

  resources :dashboards, only: [:show, :edit, :update]

  get '/profile/:username', to: 'pages#profile', as: 'profile'

  resources :chats, only: [:index, :show, :create] do
     resources :messages, only: [:index, :create]
  end

  mount ActionCable.server => '/cable'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    # @reviews = policy_scope(Review).where(rated_event_user_id:)
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @event_user = EventUser.find(params[:event_user_id])
    # @rated_event_user = User.find(@event_user.user_id)
    @review = Review.new(review_params.merge(event_user_id: params[:event_user_id], rating_event_user_id: current_user.id, rated_event_user_id: @event_user.user_id))
    authorize @review
    if @review.save
      redirect_to court_event_path(id: params[:event_id])
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating)
  end
end

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10-col-sm-12 form-signin mt-3">
    <h3>New review</h3>
      <%= form_for @review, url: court_event_event_user_reviews_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :rating %>
          <%= f.number_field :rating, max: 10, class: 'form-control' %>
        </div>

        <%= f.submit "Submit", class: 'all-buttons pink-button text-center large-button' %>
      <% end %>
    </div>
  </div>
</div>